export interface IPrelimApplicationData {
    id: Number | undefined,
    status: String | undefined,
    createdBy: Number | undefined,
    createdByName: String | undefined,
    parentId: Number | undefined,
    createdOn: String | undefined,
    detailedApplicationCreatedOn: String | undefined,
    updatedBy: String | undefined,
    updatedOn: String | undefined,
    nameOfTheFund: String | undefined,
    sponsor: String | undefined,
    investmentManager: String | undefined,
    fundManager: Number | undefined,
    dealType: Number | undefined,
    impact: Number | undefined,
    aifCategory: Number | undefined,
    nameOfTrustee: String | undefined,
    dateOfFilingWithSEBI: String | undefined,
    contributionSought: Number | undefined,
    termOfFund: Number | undefined,
    commitmentPeriod: Number | undefined,
    preferredReturn: Number | undefined,
    managementFees: Number | undefined,
    carriedInterest: Number | undefined,
    dealSector: Number | undefined,
    dealSubsector: String | undefined,
    description: String | undefined,
    investmentStrategy: String | undefined,
    sdPvtPlacementMemorandum: String | undefined,
    sdImAgreement: String | undefined,
    sdTrustDeal: String | undefined,
    sdSEBICertificate: String | undefined,
    sdDescription: String | undefined,
    sdTargetCorpusDomestic: Number | undefined,
    sdTargetCorpusOverseas: Number | undefined,
    sdTotalTargetCorpus: Number | undefined,
    sdGreenShoeTargetCorpusDomestic: Number | undefined,
    sdGreenShoeTargetCorpusOverseas: Number | undefined,
    sdGreenShoeTotalTargetCorpus: Number | undefined,
    sdFirstClosingDomesticAmount: Number | undefined,
    sdFirstClosingDomesticAmountDate: Number | undefined,
    sdFirstClosingOverseasAmount: Number | undefined,
    sdFirstCorpusOverseasAmountDate: String | undefined,
    investmentTrackRecord: String | undefined,
    declarationAccepted: boolean,
    firstClosing: boolean,
    stage: String | undefined,
    detailedApplicationId: Number | undefined,
}

export const defaultIPrelimApplicationData : IPrelimApplicationData = {
  id: undefined,
  status:  undefined,
  createdBy:  undefined,
  createdByName: undefined,
  parentId:  undefined,
  createdOn:  undefined,
  detailedApplicationCreatedOn: undefined,
  updatedBy:  undefined,
  updatedOn:  undefined,
  nameOfTheFund:  undefined,
  sponsor:  undefined,
  investmentManager:  undefined,
  fundManager:  undefined,
  dealType:  undefined,
  impact:  undefined,
  aifCategory:  undefined,
  nameOfTrustee:  undefined,
  dateOfFilingWithSEBI:  undefined,
  contributionSought:  undefined,
  termOfFund:  undefined,
  commitmentPeriod:  undefined,
  preferredReturn:  undefined,
  managementFees:  undefined,
  carriedInterest:  undefined,
  dealSector:  undefined,
  dealSubsector:  undefined,
  description:  undefined,
  investmentStrategy:  undefined,
  sdPvtPlacementMemorandum:  undefined,
  sdImAgreement:  undefined,
  sdTrustDeal:  undefined,
  sdSEBICertificate:  undefined,
  sdDescription:  undefined,
  sdTargetCorpusDomestic:  undefined,
  sdTargetCorpusOverseas:  undefined,
  sdTotalTargetCorpus:  undefined,
  sdGreenShoeTargetCorpusDomestic: undefined,
  sdGreenShoeTargetCorpusOverseas: undefined,
  sdGreenShoeTotalTargetCorpus: undefined,
  sdFirstClosingDomesticAmount:  undefined,
  sdFirstClosingDomesticAmountDate:  undefined,
  sdFirstClosingOverseasAmount:  undefined,
  sdFirstCorpusOverseasAmountDate:  undefined,
  investmentTrackRecord:  undefined,
  declarationAccepted: false,
  firstClosing: false,
  stage: undefined,
  detailedApplicationId: undefined,
}

export interface IApplicationData {
  id: Number | undefined,
  statusComments: String | undefined,
  status: String | undefined,
}